// Copyright 2012 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export var ARGUMENT_LIST = 'ARGUMENT_LIST';
export var ARRAY_COMPREHENSION = 'ARRAY_COMPREHENSION';
export var ARRAY_LITERAL_EXPRESSION = 'ARRAY_LITERAL_EXPRESSION';
export var ARRAY_PATTERN = 'ARRAY_PATTERN';
export var ARROW_FUNCTION_EXPRESSION = 'ARROW_FUNCTION_EXPRESSION';
export var AT_NAME_EXPRESSION = 'AT_NAME_EXPRESSION';
export var AT_NAME_DECLARATION = 'AT_NAME_DECLARATION';
export var AWAIT_STATEMENT = 'AWAIT_STATEMENT';
export var BINARY_OPERATOR = 'BINARY_OPERATOR';
export var BIND_THIS_PARAMETER = 'BIND_THIS_PARAMETER';
export var BINDING_ELEMENT = 'BINDING_ELEMENT';
export var BINDING_IDENTIFIER = 'BINDING_IDENTIFIER';
export var BLOCK = 'BLOCK';
export var BREAK_STATEMENT = 'BREAK_STATEMENT';
export var CALL_EXPRESSION = 'CALL_EXPRESSION';
export var CASCADE_EXPRESSION = 'CASCADE_EXPRESSION';
export var CASE_CLAUSE = 'CASE_CLAUSE';
export var CATCH = 'CATCH';
export var CLASS_DECLARATION = 'CLASS_DECLARATION';
export var CLASS_EXPRESSION = 'CLASS_EXPRESSION';
export var COMMA_EXPRESSION = 'COMMA_EXPRESSION';
export var COMPREHENSION_FOR = 'COMPREHENSION_FOR';
export var CONDITIONAL_EXPRESSION = 'CONDITIONAL_EXPRESSION';
export var CONTINUE_STATEMENT = 'CONTINUE_STATEMENT';
export var DEBUGGER_STATEMENT = 'DEBUGGER_STATEMENT';
export var DEFAULT_CLAUSE = 'DEFAULT_CLAUSE';
export var DO_WHILE_STATEMENT = 'DO_WHILE_STATEMENT';
export var EMPTY_STATEMENT = 'EMPTY_STATEMENT';
export var EXPORT_DECLARATION = 'EXPORT_DECLARATION';
export var EXPORT_MAPPING_LIST = 'EXPORT_MAPPING_LIST';
export var EXPORT_MAPPING = 'EXPORT_MAPPING';
export var EXPORT_SPECIFIER = 'EXPORT_SPECIFIER';
export var EXPORT_SPECIFIER_SET = 'EXPORT_SPECIFIER_SET';
export var EXPORT_STAR = 'EXPORT_STAR';
export var EXPRESSION_STATEMENT = 'EXPRESSION_STATEMENT';
export var FINALLY = 'FINALLY';
export var FOR_OF_STATEMENT = 'FOR_OF_STATEMENT';
export var FOR_IN_STATEMENT = 'FOR_IN_STATEMENT';
export var FORMAL_PARAMETER_LIST = 'FORMAL_PARAMETER_LIST';
export var FOR_STATEMENT = 'FOR_STATEMENT';
export var FUNCTION_DECLARATION = 'FUNCTION_DECLARATION';
export var GENERATOR_COMPREHENSION = 'GENERATOR_COMPREHENSION';
export var GET_ACCESSOR = 'GET_ACCESSOR';
export var IDENTIFIER_EXPRESSION = 'IDENTIFIER_EXPRESSION';
export var IF_STATEMENT = 'IF_STATEMENT';
export var IMPORT_DECLARATION = 'IMPORT_DECLARATION';
export var IMPORT_BINDING = 'IMPORT_BINDING';
export var IMPORT_SPECIFIER = 'IMPORT_SPECIFIER';
export var IMPORT_SPECIFIER_SET = 'IMPORT_SPECIFIER_SET';
export var LABELLED_STATEMENT = 'LABELLED_STATEMENT';
export var LITERAL_EXPRESSION = 'LITERAL_EXPRESSION';
export var MEMBER_EXPRESSION = 'MEMBER_EXPRESSION';
export var MEMBER_LOOKUP_EXPRESSION = 'MEMBER_LOOKUP_EXPRESSION';
export var MISSING_PRIMARY_EXPRESSION = 'MISSING_PRIMARY_EXPRESSION';
export var MODULE_DECLARATION = 'MODULE_DECLARATION';
export var MODULE_DEFINITION = 'MODULE_DEFINITION';
export var MODULE_EXPRESSION = 'MODULE_EXPRESSION';
export var MODULE_REQUIRE = 'MODULE_REQUIRE';
export var MODULE_SPECIFIER = 'MODULE_SPECIFIER';
export var NAME_STATEMENT = 'NAME_STATEMENT';
export var NEW_EXPRESSION = 'NEW_EXPRESSION';
export var NULL_TREE = 'NULL_TREE';
export var OBJECT_LITERAL_EXPRESSION = 'OBJECT_LITERAL_EXPRESSION';
export var OBJECT_PATTERN_FIELD = 'OBJECT_PATTERN_FIELD';
export var OBJECT_PATTERN = 'OBJECT_PATTERN';
export var PAREN_EXPRESSION = 'PAREN_EXPRESSION';
export var POSTFIX_EXPRESSION = 'POSTFIX_EXPRESSION';
export var PROGRAM = 'PROGRAM';
export var PROPERTY_METHOD_ASSIGNMENT = 'PROPERTY_METHOD_ASSIGNMENT';
export var PROPERTY_NAME_ASSIGNMENT = 'PROPERTY_NAME_ASSIGNMENT';
export var PROPERTY_NAME_SHORTHAND = 'PROPERTY_NAME_SHORTHAND';
export var QUASI_LITERAL_EXPRESSION = 'QUASI_LITERAL_EXPRESSION';
export var QUASI_LITERAL_PORTION = 'QUASI_LITERAL_PORTION';
export var QUASI_SUBSTITUTION = 'QUASI_SUBSTITUTION';
export var REST_PARAMETER = 'REST_PARAMETER';
export var RETURN_STATEMENT = 'RETURN_STATEMENT';
export var SET_ACCESSOR = 'SET_ACCESSOR';
export var STATE_MACHINE = 'STATE_MACHINE';
export var SPREAD_EXPRESSION = 'SPREAD_EXPRESSION';
export var SPREAD_PATTERN_ELEMENT = 'SPREAD_PATTERN_ELEMENT';
export var SUPER_EXPRESSION = 'SUPER_EXPRESSION';
export var SWITCH_STATEMENT = 'SWITCH_STATEMENT';
export var THIS_EXPRESSION = 'THIS_EXPRESSION';
export var THROW_STATEMENT = 'THROW_STATEMENT';
export var TRY_STATEMENT = 'TRY_STATEMENT';
export var UNARY_EXPRESSION = 'UNARY_EXPRESSION';
export var VARIABLE_DECLARATION_LIST = 'VARIABLE_DECLARATION_LIST';
export var VARIABLE_DECLARATION = 'VARIABLE_DECLARATION';
export var VARIABLE_STATEMENT = 'VARIABLE_STATEMENT';
export var WHILE_STATEMENT = 'WHILE_STATEMENT';
export var WITH_STATEMENT = 'WITH_STATEMENT';
export var YIELD_EXPRESSION = 'YIELD_EXPRESSION';
export var YIELD_STATEMENT = 'YIELD_STATEMENT';
